version: '3'

services:

  mysql:
    platform: linux/x86_64 # M1チップ対応のため追記
    # build: ./mysql/
    image: mariadb
    # image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    # hostname: localhost
    # command: mysqld --skip-grant-tables --skip-networking
    environment:
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data/redis:/data"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

volumes:
    db_data: {}
    redis_data: {}